### ISSUE TITLE
`make memcheck` errors

### ISSUE THREAD

**Issue by andrewkern** [grahamgower/demes-c#21]
back with more to report @grahamgower!

i'm getting a whole raft of errors with `make memcheck`

After passing `make test` and `make pytest`, `make memcheck` is giving me stuff like:

```
memcheck_invalid: test-cases/invalid/bad_migration_start_end_times_03.yaml
line 1: generation_time: expected a number
line 1: generation_time: expected a number
failed while loading test-cases/invalid/bad_generation_time_03.yaml
line 2: must have 0 >= selfing_rate >= 0
failed while loading test-cases/invalid/bad_generation_time_02.yaml
line 2: dest: expected a string
failed while loading test-cases/invalid/bad_toplevel_defaults_epoch_24.yaml
line 2: must have 0 >= selfing_rate >= 0
failed while loading test-cases/invalid/bad_toplevel_defaults_migration_23.yaml
deme deme1: epochs[0]: must have infinity > start_size > 0
failed while loading test-cases/invalid/bad_toplevel_defaults_epoch_31.yaml
line 2: name: expected a string
line 2: proportions: expected a list
failed while loading test-cases/invalid/bad_size_01.yaml
line 2: end_time: expected a number
line 2: cloning_rate: expected a number
line 9: proportions: expected a list of numbers
failed while loading test-cases/invalid/bad_deme_name_10.yaml
generation_time is a required field when time_units are not generations
failed while loading test-cases/invalid/bad_toplevel_defaults_pulse_19.yaml
failed while loading test-cases/invalid/bad_toplevel_defaults_epoch_06.yaml
line 10: demes: expected a list
line 4: must have infinity > end_size > 0
.
.
.
```

what am i doing wrong here?

**Comment by grahamgower** [comment]
This is actually expected. Those are the error messages on stderr from trying to load each of the invalid test cases. But valgrind errors also go to stderr and we want to see these if they occur. It's pretty noisy, but silencing the errors will also hide any valigrind output. Maybe there's a better way to organise these valgrind tests.

**Comment by andrewkern** [comment]
okay, right on. sounds like it's working then.

might be helpful to the user if the memcheck tests, said "pass" or something. i'm gonna close this issue.

**Comment by grahamgower** [comment]
I see valgrind has a `--log-file` option, so it would probably be better to use that and silence the stderr output. For now though, the return code from running `make memcheck` will be zero for success, and non-zero for failure (plus a bunch of valgrind error messages at the end of the output).

**Comment by grahamgower** [comment]
Ok, I've update the memcheck to use valgrind's --log-file option and redirect the resolver errors to /dev/null. The valgrind log file will then be printed to the terminal only if there are memory errors.
